task_order:
  - HOMING
  - BOARD_DETECTION
  - PRESS_RED_BUTTON
  - MOVE_SLIDER
  - MOVE_PLUG_CABLE
  - OPEN_DOOR
  - PROBE                   
  - STOW_PROBE_CABLE
  - PRESS_BLUE_BUTTON
  - HOMING
  - EXIT