PROJECT
git@gitlab.iit.it:hrii/projects/robothon/hrii_task_board_fsm.git: main
DEPENDENCIES
git@gitlab.iit.it:hrii/robotics/franka/franka_controllers.git: 0.10.1 (22b5d8b)
git@gitlab.iit.it:hrii/robotics/franka/franka_ros.git: 0.10.1 (f2024c3)
git@gitlab.iit.it:hrii/robotics/grippers/hrii_franka_gripper.git: noetic-devel (5dc5540)
git@gitlab.iit.it:hrii/general/hrii_gazebo_utils.git: noetic-devel (9d04307)
git@gitlab.iit.it:hrii/sensors/hrii_realsense_ros.git: noetic-devel (d17a232)
git@gitlab.iit.it:hrii/projects/robothon/hrii_robothon_gripper_description.git: main (addc5e4)
git@gitlab.iit.it:hrii/projects/robothon/hrii_robothon_msgs.git: main (fd0155e)
git@gitlab.iit.it:hrii/robotics/common/hrii_robot_interface.git: noetic-devel (60a911b)
git@gitlab.iit.it:hrii/robotics/common/hrii_robot_msgs.git: noetic-devel (3b9ced6)
git@gitlab.iit.it:hrii/projects/robothon/hrii_task_board_description.git: main (26702b6)
git@gitlab.iit.it:hrii/planning/hrii_trajectory_planner.git: noetic-devel (5ef0eab)
git@gitlab.iit.it:hrii/general/hrii_utils.git: noetic-devel (a07b7b9)
