PROJECT
git@gitlab.iit.it:hrii/projects/robothon/hrii_task_board_fsm.git: main
DEPENDENCIES
git@gitlab.iit.it:hrii/robotics/franka/franka_ros.git: 0.8.2-merge-0.10.2 (6f2f42e)
git@gitlab.iit.it:hrii/general/hrii_gazebo_utils.git: noetic-devel (2ece0a9)
git@gitlab.iit.it:hrii/robotics/common/hrii_robot_interface.git: noetic-devel (3b4995d)
git@gitlab.iit.it:hrii/robotics/common/hrii_robot_msgs.git: noetic-devel (6738cd9)
git@gitlab.iit.it:hrii/projects/robothon/hrii_board_description.git: main (3a9b9e3)
git@gitlab.iit.it:hrii/planning/hrii_trajectory_planner.git: noetic-devel (7fc0c78)
git@gitlab.iit.it:hrii/general/hrii_utils.git: noetic-devel (00216d6)
