PROJECT
git@gitlab.iit.it:hrii/projects/robothon/hrii_task_board_fsm.git: main
DEPENDENCIES
git@gitlab.iit.it:hrii/robotics/franka/franka_ros.git: 0.10.1-franka_controller (ee1b31b)
git@gitlab.iit.it:hrii/projects/robothon/hrii_board_description.git: main (3a9b9e3)
git@gitlab.iit.it:hrii/general/hrii_gazebo_utils.git: noetic-devel (2ece0a9)
git@gitlab.iit.it:hrii/robotics/common/hrii_robot_interface.git: noetic-devel (3b4995d)
git@gitlab.iit.it:hrii/robotics/common/hrii_robot_msgs.git: noetic-devel (3b9ced6)
git@gitlab.iit.it:hrii/planning/hrii_trajectory_planner.git: noetic-devel (7fc0c78)
git@gitlab.iit.it:hrii/general/hrii_utils.git: noetic-devel (00216d6)
